apisix:
  node_listen: ${{APISIX_NODE_LISTEN:=9080}} # APISIX listening port
  enable_ipv6: false

  enable_control: true
  control:
    ip: "${{APISIX_CONTROL_IP:=0.0.0.0}}"
    port: ${{APISIX_CONTROL_PORT:=9090}}

deployment:
  admin:
    allow_admin: # https://nginx.org/en/docs/http/ngx_http_access_module.html#allow
      - 0.0.0.0/0 # We need to restrict ip access rules for security. 0.0.0.0/0 is for test.

    admin_listen:
      port: ${{DEPLOYMENT_ADMIN_ADMIN_LISTEN:=9180}}

    admin_key:
      - name: "admin"
        key: ${{DEPLOYMENT_ADMIN_ADMIN_KEY:=supersecretadminkey}}
        role: admin # admin: manage all configuration data

      - name: "viewer"
        key: ${{DEPLOYMENT_ADMIN_VIEWER_KEY:=supersecretviewerkey}}
        role: viewer

  etcd:
    host: # it's possible to define multiple etcd hosts addresses of the same etcd cluster.
      - "http://etcd:2379" # multiple etcd address
    # user: ${{ETCD_ROOT_USER:=root}} # username for etcd
    # password: ${{ETCD_ROOT_PASS:=etcd_password}} # password for etcd
    prefix: "/apisix" # apisix configurations prefix
    timeout: 30 # 30 seconds
